import type { Metadata } from "next";
import "./globals.css";
import { Exo, Space_Grotesk } from "next/font/google"; // Of een ander heading font
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import {Toaster} from "@/components/ui/sonner"
import Navbar from "@/components/navbar";


const exo = Exo({
    variable: "--font-exo",
    subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
    variable: "--font-space-grotesk",
    subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
        lang="en" suppressHydrationWarning className={`${exo.variable} ${spaceGrotesk.variable}`}
    >
      <body className="antialiased">
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
          <div className="flex flex-col min-h-screen relative overflow-hidden">
          <Navbar/>

              <main className="flex-1 flex items-center justify-center">
                  {children}
              </main>

              <Toaster richColors/>
          </div>
      </ThemeProvider>
      </body>
    </html>
  );
}

