import type { Metadata } from "next";
import "./globals.css";
import { Exo, Space_Grotesk } from "next/font/google"; // Of een ander heading font
import "./globals.css";
import {auth} from "@/auth";

const exo = Exo({
    variable: "--font-exo",
    subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
    variable: "--font-space-grotesk",
    subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await auth()
  return (
    <html
        lang="en" suppressHydrationWarning className={`${exo.variable} ${spaceGrotesk.variable}`}
    >
      <body className="antialiased">
      <div>{session?.user?.email ?? "No user logged in"}</div>
      {children}
      </body>
    </html>
  );
}
